### ISSUE TITLE
see paper.md for comments

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-342#1]

**Comment by HBoles20** [comment]
I addressed all issues mentioned.

**Comment by laszewsk** [comment]
see https://github.com/cybertraining-dsc/fa20-523-342/runs/1580807352?check_suite_focus=true

**Comment by HBoles20** [comment]
I have fixed all issues, I have a problem with the images are not showing in the report. I also tried to submit the link in canvas but looks like the assignment is locked.

**Comment by laszewsk** [comment]
see example from template... yours do not look like this

```![database sample](https://github.com/cybertraining-dsc/fa20-523-312/raw/main/project/images/sampledatabase.png)```

**Comment by laszewsk** [comment]
also all image file names must be lower case JPG is upper case

**Comment by HBoles20** [comment]
I have fixed the intext citation to match the sample, I also fixed the images. I really appreciate all your help.
